services:
  api:
    build: .
    container_name: fastapi
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./src:/code/src
      - ./.vscode:/code/.vscode
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=fastapi_app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    command: ./init.sh

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fastapi_app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--host=localhost" ]
      interval: 45s
      retries: 5
      start_period: 30s
      timeout: 10s
    command: mysqld
